### ISSUE TITLE
Status of developments

### ISSUE THREAD

**Issue by bartbutenaers** [HendrikRoth/node-red-contrib-onvif#1]
Hi Hendrik (@HendrikRoth),

I was wondering about the status of your OnVif contribution.  Do you have already something usable?  If so, it would be great if you could share your developments in this repository!

Have been looking this evening at [node-onvif](https://github.com/futomi/node-onvif), but it would be even better if you had already some Node-Red specific stuff ...

Thanks in advance !!
Bart Butenaers

**Comment by HendrikRoth** [comment]
Hello @bartbutenaers ,
i was looking for writing an plugin, but realised than that my ordered webcam does not have onvif.
So there is no code at the moment, sorry.

**Comment by bartbutenaers** [comment]
Hi Hendrik (@HendrikRoth),
Thanks for the reply.  No problem.  Yesterday I started writing my own OnVif nodes for Node-Red.  Do you mind if I publish that contribution as '**node-red-contrib-onvif**' ?

**Comment by HendrikRoth** [comment]
No, absolutely no problem. i remove this repo here :-)
